engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  tslint:
    enabled: true
    config: tslint.json
    channel: "beta"
  fixme:
    enabled: true
ratings:
  paths:
  - "src/*.ts"
exclude_paths:
  - ".*"
  - "**/*.*"
  - "!src/**/*.ts"
  - "src/**/*.spec.ts"
