plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript

  eslint:
    enabled: true

  fixme:
    enabled: true

exclude_patterns:
  - "LICENSE"
  - ".*"
  - "**/*.*"
  - "!**/*.js"
