language: node_js

node_js:
  - "8"

before_script:
  - npm install
  - npm run test

script:
  - npm run build

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

