language: node_js

node_js:
  - "8"

before_script:
  - npm install
  - npm install codeclimate-test-reporter

script:
  - npm run test
  - codeclimate-test-reporter < coverage/lcov.info

  - npm run build
  - npm prune --production

deploy:
  provider: npm
    email: $CodeY_NPM_RELEASE_EMAIL
    api_key: $CodeY_NPM_RELEASE_AUTHTOKEN
  on:
    branch: master
    tags: true

