language: node_js

node_js:
  - "8"

before_script:
  - npm install
  - npm install codeclimate-test-reporter

script:
  - npm run test
  - codeclimate-test-reporter < coverage/lcov.info

  - npm run build
  - npm run prune --production

after_script:

